# Configure main menu and social menu
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/seymenkonuk"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://linkedin.com/in/recepseymenkonuk"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "gmail"
name = "Gmail"
url = "mailto:konukrecepseymen@gmail.com"

[social.params]
icon = "brand-gmail"
